### ISSUE TITLE
Use latest release instead of a hard-coded TAG

### ISSUE THREAD

**Issue by artempyanykh** [sublimelsp/LSP-marksman#5]
IIUC, sublime pulls in a particular release which is hard-coded in the plugin's source code. Generally, there are no breaking changes in Marksman from release to release; rather bug fixes and new features. Pulling the latest released binary would probably give a better experience overall (especially because I release pretty often).

Would it be possible to do that? Also, I'm curious if sublime LSP is able to check whether there's a newer release and suggest updating the binary?

**Comment by rchl** [comment]
Yeah, we've decided to have a convention for LSP-* packages where the server version is pinned and updated together with new package version.

That way we can also tie upgrading to normal Package Control upgrading mechanism rather than asking user to upgrade or doing update checks before every start (as @jfcherng said).

The process is not optimal as for npm-based packages. For those we can set up automatic new-version notifications and make dependabot auto-create PRs to update them. Here we can miss updates easily unless we find some helpful github action or write one ourselves.

**Comment by artempyanykh** [comment]
Thanks @rchl @jfcherng, it makes sense. It seems that a GH action that would auto bump the version here when a new Marksman is released would be ideal.

**Comment by rchl** [comment]
I couldn't find any github actions that could track and ping on new GitHub releases. Also tools like Renovate don't seem to support it.

I guess that either someone can find a github action for this or there is also an option for setting up a workflow on marksman repo that would notify this repo on new releases. That way it shouldn't be that hard.

**Comment by artempyanykh** [comment]
> setting up a workflow on marksman repo that would notify this repo on new releases

@rchl do you have any pointers as to how I could set up such a workflow?

**Comment by rchl** [comment]
I think you could set up the https://github.com/marketplace/actions/repository-dispatch action on your side and this repo would need to set up a `repository_dispatch` workflow. And we would need to create an access token that you would use in your action.

Our workflow could automatically create a PR with the change if your workflow would send the new tag. An related example is here: https://github.com/sublimelsp/repository/blob/ccc25996a2ee05d70457344219a6dd62130ad2ac/.github/workflows/on-new-release.yml
